# Generated by Django 3.0.2 on 2020-02-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200205_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_item',
            name='user_id',
        ),
    ]
