# Generated by Django 3.0.2 on 2020-01-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_customer', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('table_num', models.CharField(max_length=50)),
                ('number_of_customer', models.IntegerField(default='0')),
                ('Date', models.DateField()),
            ],
        ),
    ]
