# Generated by Django 3.0.2 on 2020-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='Time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='book_table',
            name='contact_number',
            field=models.CharField(max_length=50),
        ),
    ]
