# Generated by Django 3.0.2 on 2020-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20200124_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Second_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=20)),
                ('Date_of_birth', models.DateField()),
                ('Remember_me', models.BooleanField()),
            ],
        ),
    ]
