# Generated by Django 3.0.2 on 2020-02-01 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_registration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_desc', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Registration_table')),
            ],
        ),
    ]
