# Generated by Django 3.0.2 on 2020-02-02 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
