# Generated by Django 3.0.2 on 2020-02-07 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_auto_20200206_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 2, 7, 4, 57, 26, 545029, tzinfo=utc)),
        ),
    ]
